version: '3.8'

services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"  # Port for RabbitMQ clients
#      - "15672:15672"  # Port for RabbitMQ management UI
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#    restart: unless-stopped

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    depends_on:
      - recommendations
      # - interactions
    ports:
      - "8001:8000"
    volumes:
     - ./webapp/logs:/logs
    environment:
     - PYTHONUNBUFFERED=1
    env_file:
      - .env

  recommendations:
      build:
        context: ./recommendations
        dockerfile: Dockerfile
      container_name: recommendations
      ports:
        - "${REC_SERVICE_PORT}:8000"
      volumes:
        - ./recommendations/logs:/logs
      environment:
        - PYTHONUNBUFFERED=1
      env_file:
        - .env

volumes:
  rabbitmq_data: